apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: orthophoto-with-tiling
spec:
  inputs:
    resources:
    - name: image-dataset
      type: git
      targetPath: /dataset
  steps:
  - name: odm-orthophoto
    image: opendronemap/odm
    args:
    - dataset
    - --project-path
    - /workspace
    - --min-num-features
    - "1000"
    - --skip-3dmodel
    - --mesh-size
    - "20000"
    - --fast-orthophoto
    - --time
  - name: map-tile-gen
    image: osgeo/gdal
    workingDir: /workspace
    script: |
      #!/usr/bin/env bash
      gdal2tiles.py -w leaflet ./dataset/odm_orthophoto/odm_orthophoto.original.tif ./dataset/odm_orthophoto/tiles
  - name: tar-and-store
    image: ubuntu
    workingDir: /workspace
    script: |
      #!/usr/bin/env bash
      TIME_STAMP=$(date | tr ' ' '_' | tr ':' '.')
      tar -cvf ${TIME_STAMP}.tar ./dataset/odm_orthophoto

      mkdir -p /usr/share/nginx/html/data/${TIME_STAMP}
      mv ${TIME_STAMP}.tar /usr/share/nginx/html/data/${TIME_STAMP}/${TIME_STAMP}.tar
      cd /usr/share/nginx/html/data/${TIME_STAMP}

      tar -xvf ${TIME_STAMP}.tar
      echo before
      cat /usr/share/nginx/html/index.html

      sed -i '/<\/body>/i <a href="/data/'${TIME_STAMP}'/dataset/odm_orthophoto/tiles/leaflet.html">'${TIME_STAMP}' view map </a><hr>' /usr/share/nginx/html/index.html

      echo after
      echo ${TIME_STAMP}
      cat /usr/share/nginx/html/index.html
    volumeMounts:
    - name: odm-persistent-storage
      mountPath: "/usr/share/nginx/html"
  volumes:
  - name: odm-persistent-storage
    persistentVolumeClaim:
      claimName: odm-storage-pv-claim

