apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: ortho-tiles-
spec:
  taskRef:
    name: orthophoto-with-tiling
  inputs:
    resources:
    - name: image-dataset
      resourceRef:
        name: aukerman-git-repo
